server:
  port: 8088 #服务端口
spring:
  application:
    name: eurekaServer #eureka服务名称
eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://127.0.0.1:8088/eureka
    register-with-eureka: true  # 是否注册自己的信息到EurekaServer，默认是true
    fetch-registry: true # 是否拉取其它服务的信息，默认是true
